openapi: 3.0.0
info:
  title: Sequencer API
  version: 1.0.0
servers:
  - url: http://localhost:5000/api/v1
paths:
  /messages:
    post:
      summary: Assigns a sequence number to a message and forwards it to the shuffler.
      requestBody:
        description: The message with bank account transaction details.
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                operation:
                  type: string
                  enum: [CREDIT, DEBIT]
                  description: The transaction type.
                amount:
                  type: integer
                  description: The transaction amount.
                  example: 10000
              required:
                - operation
                - amount
      responses:
        '200':
          description: Message forwarded successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: OK
        '400':
          description: Invalid message.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: Bad Request
        '502':
          description: Failed to contact the shuffler.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: Bad Gateway
